#!/usr/bin/env bash

nthreads=6

runspec(){
    fn=${1}
    tfile=${2}
    var=${3}
    lead=${4}
    touch ${tfile}
    lev=$(echo ${fn} | cut -d '_' -f 2)
    stream=$(echo ${fn} | cut -d '_' -f 3)
    centre=$(echo ${fn} | cut -d '_' -f 4)
    mtype=$(echo ${fn} | cut -d '_' -f 5)
    version=$(echo ${fn} | cut -d '_' -f 6)
    ./spectra.py -c ${centre} -s ${stream} -t ${mtype} -r ${version} -l ${lead} ${var} ${lev}
    rm -f ${tfile}
}

tprefix=.thread
rm -f ${tprefix}_*
for fcst in $(find forecasts -name "u_*01.grib2"); do
    sleep 1
    tfile=${tprefix}_$(basename ${fcst})
    while [[ $(ls -1 ${tprefix}* 2>/dev/null | wc -l) -ge ${nthreads} ]] ; do
	sleep 5
    done
    runspec $(basename ${fcst}) ${tfile} ke 240 &
done
wait
